// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const consumeCode = `-- name: ConsumeCode :exec
UPDATE otp_codes
SET consumed_at = now()
WHERE id = $1
`

func (q *Queries) ConsumeCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeCode, id)
	return err
}

const consumeCodes = `-- name: ConsumeCodes :exec
UPDATE otp_codes
SET consumed_at = now()
WHERE user_id = $1 AND consumed_at IS NULL
`

// ConsumeCodes makes every code of one user useless, which happens as soon as
// a new code goes out.
func (q *Queries) ConsumeCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeCodes, userID)
	return err
}

const countCodeAttempt = `-- name: CountCodeAttempt :one
UPDATE otp_codes
SET attempts = attempts + 1
WHERE id = $1
RETURNING attempts
`

func (q *Queries) CountCodeAttempt(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countCodeAttempt, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const countCredentials = `-- name: CountCredentials :one
SELECT count(*) FROM webauthn_credentials
WHERE user_id = $1
`

func (q *Queries) CountCredentials(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCredentials, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChallenge = `-- name: CreateChallenge :exec
INSERT INTO webauthn_challenges (id, user_id, purpose, data, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateChallengeParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	Data      []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) error {
	_, err := q.db.Exec(ctx, createChallenge,
		arg.ID,
		arg.UserID,
		arg.Purpose,
		arg.Data,
		arg.ExpiresAt,
	)
	return err
}

const createCode = `-- name: CreateCode :exec
INSERT INTO otp_codes (id, user_id, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateCodeParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CodeHash  []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateCode(ctx context.Context, arg CreateCodeParams) error {
	_, err := q.db.Exec(ctx, createCode,
		arg.ID,
		arg.UserID,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const createCredential = `-- name: CreateCredential :exec
INSERT INTO webauthn_credentials (credential_id, user_id, data)
VALUES ($1, $2, $3)
`

type CreateCredentialParams struct {
	CredentialID []byte
	UserID       uuid.UUID
	Data         []byte
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) error {
	_, err := q.db.Exec(ctx, createCredential, arg.CredentialID, arg.UserID, arg.Data)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredChallenges = `-- name: DeleteExpiredChallenges :exec
DELETE FROM webauthn_challenges
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredChallenges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredChallenges)
	return err
}

const deleteExpiredCodes = `-- name: DeleteExpiredCodes :exec
DELETE FROM otp_codes
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredCodes)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getLatestCode = `-- name: GetLatestCode :one
SELECT id, user_id, code_hash, attempts, expires_at, consumed_at, created_at FROM otp_codes
WHERE user_id = $1 AND consumed_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestCode(ctx context.Context, userID uuid.UUID) (OtpCode, error) {
	row := q.db.QueryRow(ctx, getLatestCode, userID)
	var i OtpCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT users.id, users.full_name, users.email, users.created_at, users.updated_at, users.phone_number FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1 AND sessions.expires_at > now()
`

// GetSessionUser reads the person behind a live session in one step.
func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const listCredentials = `-- name: ListCredentials :many
SELECT credential_id, user_id, data, created_at, last_used_at FROM webauthn_credentials
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListCredentials(ctx context.Context, userID uuid.UUID) ([]WebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listCredentials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebauthnCredential
	for rows.Next() {
		var i WebauthnCredential
		if err := rows.Scan(
			&i.CredentialID,
			&i.UserID,
			&i.Data,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const takeChallenge = `-- name: TakeChallenge :one
DELETE FROM webauthn_challenges
WHERE id = $1 AND purpose = $2 AND expires_at > now()
RETURNING id, user_id, purpose, data, expires_at
`

type TakeChallengeParams struct {
	ID      uuid.UUID
	Purpose string
}

func (q *Queries) TakeChallenge(ctx context.Context, arg TakeChallengeParams) (WebauthnChallenge, error) {
	row := q.db.QueryRow(ctx, takeChallenge, arg.ID, arg.Purpose)
	var i WebauthnChallenge
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Purpose,
		&i.Data,
		&i.ExpiresAt,
	)
	return i, err
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE webauthn_credentials
SET data = $2, last_used_at = now()
WHERE credential_id = $1
`

type UpdateCredentialParams struct {
	CredentialID []byte
	Data         []byte
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.Exec(ctx, updateCredential, arg.CredentialID, arg.Data)
	return err
}
