// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO conversation_participants (conversation_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddParticipantParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, subject, created_by)
VALUES ($1, $2, $3)
RETURNING id, subject, created_by, created_at
`

type CreateConversationParams struct {
	ID        uuid.UUID
	Subject   string
	CreatedBy uuid.UUID
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.ID, arg.Subject, arg.CreatedBy)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, conversation_id, author_id, body)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, author_id, body, created_at
`

type CreateMessageParams struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	AuthorID       uuid.UUID
	Body           string
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ConversationID,
		arg.AuthorID,
		arg.Body,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT id, subject, created_by, created_at FROM conversations
WHERE id = $1
`

func (q *Queries) GetConversation(ctx context.Context, id uuid.UUID) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const isParticipant = `-- name: IsParticipant :one
SELECT EXISTS (
    SELECT 1 FROM conversation_participants
    WHERE conversation_id = $1 AND user_id = $2
)
`

type IsParticipantParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) IsParticipant(ctx context.Context, arg IsParticipantParams) (bool, error) {
	row := q.db.QueryRow(ctx, isParticipant, arg.ConversationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listConversations = `-- name: ListConversations :many
SELECT
    c.id,
    c.subject,
    c.created_by,
    c.created_at,
    COALESCE((
        SELECT string_agg(u.full_name, ', ' ORDER BY u.full_name)
        FROM conversation_participants other
        JOIN users u ON u.id = other.user_id
        WHERE other.conversation_id = c.id AND other.user_id <> p.user_id
    ), '')::text AS others,
    COALESCE((
        SELECT max(m.created_at) FROM messages m WHERE m.conversation_id = c.id
    ), c.created_at)::timestamptz AS last_message_at,
    (
        SELECT count(*)
        FROM messages m
        WHERE m.conversation_id = c.id
          AND m.author_id <> p.user_id
          AND (p.last_read_at IS NULL OR m.created_at > p.last_read_at)
    )::bigint AS unread
FROM conversations c
JOIN conversation_participants p ON p.conversation_id = c.id
WHERE p.user_id = $1
ORDER BY last_message_at DESC
`

type ListConversationsRow struct {
	ID            uuid.UUID
	Subject       string
	CreatedBy     uuid.UUID
	CreatedAt     time.Time
	Others        string
	LastMessageAt time.Time
	Unread        int64
}

// ListConversations reads the list of one person: the subject, the other
// people in one string, the time of the newest message, and how many messages
// this person has not read.
func (q *Queries) ListConversations(ctx context.Context, userID uuid.UUID) ([]ListConversationsRow, error) {
	rows, err := q.db.Query(ctx, listConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Others,
			&i.LastMessageAt,
			&i.Unread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT
    m.id,
    m.author_id,
    u.full_name AS author_name,
    m.body,
    m.created_at
FROM messages m
JOIN users u ON u.id = m.author_id
WHERE m.conversation_id = $1
ORDER BY m.created_at, m.id
`

type ListMessagesRow struct {
	ID         uuid.UUID
	AuthorID   uuid.UUID
	AuthorName string
	Body       string
	CreatedAt  time.Time
}

func (q *Queries) ListMessages(ctx context.Context, conversationID uuid.UUID) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.AuthorName,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipants = `-- name: ListParticipants :many
SELECT users.id, users.full_name, users.email, users.created_at, users.updated_at, users.phone_number FROM conversation_participants
JOIN users ON users.id = conversation_participants.user_id
WHERE conversation_participants.conversation_id = $1
ORDER BY users.full_name
`

func (q *Queries) ListParticipants(ctx context.Context, conversationID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listParticipants, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRead = `-- name: MarkRead :one
WITH previous AS (
    SELECT before.last_read_at
    FROM conversation_participants AS before
    WHERE before.conversation_id = $1 AND before.user_id = $2
)
UPDATE conversation_participants AS now_read
SET last_read_at = now()
WHERE now_read.conversation_id = $1 AND now_read.user_id = $2
RETURNING (SELECT previous.last_read_at FROM previous) AS previous_read_at
`

type MarkReadParams struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
}

// MarkRead notes that this person has seen the conversation up to now, and
// gives back the time it replaces. The page draws the line for the unread
// messages from that older time, so it must read the row before the update.
func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, markRead, arg.ConversationID, arg.UserID)
	var previous_read_at pgtype.Timestamptz
	err := row.Scan(&previous_read_at)
	return previous_read_at, err
}
