// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: live.sql

package db

import (
	"context"
)

const notify = `-- name: Notify :exec
SELECT pg_notify('chat_changed', $1::text)
`

// Notify tells every server instance that a conversation changed. Each one
// listens on the channel chat_changed and hands the event to its open pages.
func (q *Queries) Notify(ctx context.Context, payload string) error {
	_, err := q.db.Exec(ctx, notify, payload)
	return err
}
