// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"uuid"
)

type User struct {
	ID        uuid.UUID
	FullName  string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}
