// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"uuid"
)

type Conversation struct {
	ID        uuid.UUID
	Subject   string
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

type ConversationParticipant struct {
	ConversationID uuid.UUID
	UserID         uuid.UUID
	AddedAt        time.Time
	LastReadAt     pgtype.Timestamptz
}

type Message struct {
	ID             uuid.UUID
	ConversationID uuid.UUID
	AuthorID       uuid.UUID
	Body           string
	CreatedAt      time.Time
}

type OtpCode struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	CodeHash   []byte
	Attempts   int32
	ExpiresAt  time.Time
	ConsumedAt pgtype.Timestamptz
	CreatedAt  time.Time
}

type Session struct {
	TokenHash []byte
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID          uuid.UUID
	FullName    string
	Email       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	PhoneNumber string
}

type WebauthnChallenge struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	Data      []byte
	ExpiresAt time.Time
}

type WebauthnCredential struct {
	CredentialID []byte
	UserID       uuid.UUID
	Data         []byte
	CreatedAt    time.Time
	LastUsedAt   pgtype.Timestamptz
}
