// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package db

import (
	"context"

	"uuid"
)

const countUnread = `-- name: CountUnread :many
SELECT p.user_id, count(m.id)::bigint AS unread
FROM conversation_participants p
LEFT JOIN messages m
    ON m.conversation_id = p.conversation_id
   AND m.author_id <> p.user_id
   AND (p.last_read_at IS NULL OR m.created_at > p.last_read_at)
WHERE p.user_id = ANY($1::uuid[])
GROUP BY p.user_id
`

type CountUnreadRow struct {
	UserID uuid.UUID
	Unread int64
}

// CountUnread counts the messages from other people that each person has not
// read, over every conversation of that person. The rule is the one of the
// unread count in ListConversations. The badge on the icon of the installed
// app shows the number.
func (q *Queries) CountUnread(ctx context.Context, userIds []uuid.UUID) ([]CountUnreadRow, error) {
	rows, err := q.db.Query(ctx, countUnread, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountUnreadRow
	for rows.Next() {
		var i CountUnreadRow
		if err := rows.Scan(&i.UserID, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM push_subscriptions
WHERE endpoint = $1 AND user_id = $2
`

type DeleteSubscriptionParams struct {
	Endpoint string
	UserID   uuid.UUID
}

func (q *Queries) DeleteSubscription(ctx context.Context, arg DeleteSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteSubscription, arg.Endpoint, arg.UserID)
	return err
}

const deleteSubscriptionByEndpoint = `-- name: DeleteSubscriptionByEndpoint :exec
DELETE FROM push_subscriptions
WHERE endpoint = $1
`

// DeleteSubscriptionByEndpoint removes a browser that the push service no
// longer knows.
func (q *Queries) DeleteSubscriptionByEndpoint(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deleteSubscriptionByEndpoint, endpoint)
	return err
}

const getVAPIDKeys = `-- name: GetVAPIDKeys :one
SELECT public_key, private_key FROM vapid_keys
WHERE id = 1
`

type GetVAPIDKeysRow struct {
	PublicKey  string
	PrivateKey string
}

func (q *Queries) GetVAPIDKeys(ctx context.Context) (GetVAPIDKeysRow, error) {
	row := q.db.QueryRow(ctx, getVAPIDKeys)
	var i GetVAPIDKeysRow
	err := row.Scan(&i.PublicKey, &i.PrivateKey)
	return i, err
}

const insertVAPIDKeys = `-- name: InsertVAPIDKeys :exec
INSERT INTO vapid_keys (id, public_key, private_key)
VALUES (1, $1, $2)
ON CONFLICT (id) DO NOTHING
`

type InsertVAPIDKeysParams struct {
	PublicKey  string
	PrivateKey string
}

// InsertVAPIDKeys writes a pair unless one is already there. Two instances
// that start together both read the pair afterwards, so they agree.
func (q *Queries) InsertVAPIDKeys(ctx context.Context, arg InsertVAPIDKeysParams) error {
	_, err := q.db.Exec(ctx, insertVAPIDKeys, arg.PublicKey, arg.PrivateKey)
	return err
}

const listSubscriptionsForUsers = `-- name: ListSubscriptionsForUsers :many
SELECT ps.user_id, ps.endpoint, ps.p256dh, ps.auth
FROM push_subscriptions ps
JOIN sessions s ON s.token_hash = ps.session_key
WHERE ps.user_id = ANY($1::uuid[])
  AND s.expires_at > now()
ORDER BY ps.created_at
`

type ListSubscriptionsForUsersRow struct {
	UserID   uuid.UUID
	Endpoint string
	P256dh   string
	Auth     string
}

// ListSubscriptionsForUsers reads the browsers of some people. A browser
// whose session ran out hears nothing, although its row is still there.
func (q *Queries) ListSubscriptionsForUsers(ctx context.Context, userIds []uuid.UUID) ([]ListSubscriptionsForUsersRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionsForUsersRow
	for rows.Next() {
		var i ListSubscriptionsForUsersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSubscription = `-- name: UpsertSubscription :exec
INSERT INTO push_subscriptions (id, user_id, session_key, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (endpoint) DO UPDATE
SET user_id     = excluded.user_id,
    session_key = excluded.session_key,
    p256dh      = excluded.p256dh,
    auth        = excluded.auth
`

type UpsertSubscriptionParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	SessionKey []byte
	Endpoint   string
	P256dh     string
	Auth       string
}

// UpsertSubscription stores a browser. A browser that sends the same endpoint
// again moves to the person and the session that send it now.
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) error {
	_, err := q.db.Exec(ctx, upsertSubscription,
		arg.ID,
		arg.UserID,
		arg.SessionKey,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}
