// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remind.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const claimReminders = `-- name: ClaimReminders :many
WITH due AS (
    SELECT p.user_id, p.conversation_id
    FROM conversation_participants p
    JOIN users u ON u.id = p.user_id
    WHERE u.sms_reminders
      AND u.phone_number <> ''
      AND NOT ($1::boolean AND u.quiet_nights)
      AND EXISTS (
          SELECT 1 FROM messages m
          WHERE m.conversation_id = p.conversation_id
            AND m.author_id <> p.user_id
            AND m.created_at > coalesce(p.last_read_at, '-infinity'::timestamptz)
            AND m.created_at > $2::timestamptz
            AND m.created_at <= $3::timestamptz
      )
      AND NOT EXISTS (
          SELECT 1 FROM push_subscriptions ps
          JOIN sessions s ON s.token_hash = ps.session_key
          WHERE ps.user_id = p.user_id AND s.expires_at > now()
      )
      AND NOT EXISTS (
          SELECT 1 FROM sms_reminders r
          WHERE r.user_id = p.user_id
            AND r.conversation_id = p.conversation_id
            AND r.sent_at > coalesce(p.last_read_at, '-infinity'::timestamptz)
      )
),
claimed AS (
    INSERT INTO sms_reminders (user_id, conversation_id, sent_at)
    SELECT user_id, conversation_id, now() FROM due
    ON CONFLICT (user_id, conversation_id) DO UPDATE SET sent_at = excluded.sent_at
    RETURNING user_id, conversation_id
)
SELECT
    claimed.user_id,
    claimed.conversation_id,
    u.phone_number,
    c.subject,
    -- The people who wrote what this person missed, the earliest first.
    ARRAY(
        SELECT w.full_name
        FROM messages m
        JOIN users w ON w.id = m.author_id
        WHERE m.conversation_id = claimed.conversation_id
          AND m.author_id <> claimed.user_id
          AND m.created_at > coalesce(p.last_read_at, '-infinity'::timestamptz)
        GROUP BY w.full_name
        ORDER BY min(m.created_at)
    )::text[] AS writers
FROM claimed
JOIN users u ON u.id = claimed.user_id
JOIN conversations c ON c.id = claimed.conversation_id
JOIN conversation_participants p
  ON p.conversation_id = claimed.conversation_id AND p.user_id = claimed.user_id
ORDER BY claimed.user_id, claimed.conversation_id
`

type ClaimRemindersParams struct {
	Night     bool
	NotBefore time.Time
	DueBefore time.Time
}

type ClaimRemindersRow struct {
	UserID         uuid.UUID
	ConversationID uuid.UUID
	PhoneNumber    string
	Subject        string
	Writers        []string
}

// ClaimReminders finds every person who missed a message in a conversation
// and notes the SMS for them in the same statement. A pair is due when:
//
//  1. a message from somebody else is newer than the last reading of the
//     person, and was written between not_before and due_before,
//  2. the person has no browser with a live push subscription,
//  3. the person left the SMS on and has a phone number,
//  4. no SMS for this pair went out after the last reading,
//  5. in the night, the person turned the quiet nights off.
func (q *Queries) ClaimReminders(ctx context.Context, arg ClaimRemindersParams) ([]ClaimRemindersRow, error) {
	rows, err := q.db.Query(ctx, claimReminders, arg.Night, arg.NotBefore, arg.DueBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimRemindersRow
	for rows.Next() {
		var i ClaimRemindersRow
		if err := rows.Scan(
			&i.UserID,
			&i.ConversationID,
			&i.PhoneNumber,
			&i.Subject,
			&i.Writers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockReminders = `-- name: LockReminders :one
SELECT pg_try_advisory_xact_lock(hashtext('sms_reminders'))::boolean AS locked
`

// LockReminders lets one server instance claim at a time. The lock ends
// with the transaction.
func (q *Queries) LockReminders(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, lockReminders)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
