// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, full_name, email, phone_number)
VALUES ($1, $2, $3, $4)
RETURNING id, full_name, email, created_at, updated_at, phone_number
`

type CreateUserParams struct {
	ID          uuid.UUID
	FullName    string
	Email       string
	PhoneNumber string
}

// CreateUser writes one user. The application has no way for a visitor to
// create a user yet, so the tests and the seed use this query.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.FullName,
		arg.Email,
		arg.PhoneNumber,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, full_name, email, created_at, updated_at, phone_number FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, full_name, email, created_at, updated_at, phone_number FROM users
WHERE lower(email) = lower($1::text)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, full_name, email, created_at, updated_at, phone_number FROM users
ORDER BY id
`

// The identifier is a UUID version 7, which starts with the time, so this
// order is the order of creation.
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PhoneNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserPhone = `-- name: SetUserPhone :one
UPDATE users
SET phone_number = $2, updated_at = now()
WHERE id = $1
RETURNING id, full_name, email, created_at, updated_at, phone_number
`

type SetUserPhoneParams struct {
	ID          uuid.UUID
	PhoneNumber string
}

// SetUserPhone fixes the number of a user. The seed uses it, because a
// migration cannot know the numbers.
func (q *Queries) SetUserPhone(ctx context.Context, arg SetUserPhoneParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPhone, arg.ID, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PhoneNumber,
	)
	return i, err
}
