// Package assets holds the static files that the server sends to the browser.
//
// The files are compiled into the binary, so the program needs no files next
// to it at run time. dist/styles.css is generated by the css task, and the
// repository keeps dist/.gitkeep so the embed pattern always matches a file.
package assets

import "embed"

//go:embed all:css all:js all:dist
var FS embed.FS
